name: tv24africa
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.2
  youtube_player_flutter: ^7.0.0+6
  gradient_app_bar: ^0.1.3
  settings_ui: ^0.3.0
  flutter_colorpicker: ^0.3.4
  flutter_material_color_picker: ^1.0.5
  color: any
  image_picker:
  google_fonts: ^1.1.0
  chewie:
  cached_network_image: ^2.2.0+1
  html:
  flutter_wordpress: 0.1.4
  flutter_html: 0.11.0
  connectivity: ^0.4.9
  # url_launcher: 5.1.6
  url_launcher: ^5.5.0
  provider: ^2.0.1
  video_player:


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.3"
  
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    
    - assets/images/tv.png
    - assets/images/africa this week.jpg
    - assets/images/business.jpg
    - assets/images/change majer.jpg
    - assets/images/day break.jpg
    - assets/images/sport.jpg
    - assets/images/the-investigation.jpg
    - assets/images/this is  africa.jpg
    - assets/images/trendz.jpg
    - assets/images/tv-african-news.jpg
    - assets/images/tv24.jpg
    - assets/images/woman.jpg
    - assets/images/1.jpg
    - assets/images/2.jpg
    - assets/images/3.jpg
    - assets/images/4.jpg
    - assets/images/6.png
    - assets/images/tip.jpg
    - assets/images/load.gif
    - assets/images/podcast.gif 
    # - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
